/* ============================================================
   PruTech — case study data
   Extracted verbatim from js/brand-main.js so the Featured Work
   carousel and the 3D fly-through render the same projects.
   ============================================================ */
window.PT_CASES = [
    { level: 'Commercial', cat: 'Cloud Migration', title: 'In-house Orchestration Layer', desc: 'A leading national health insurer needed a partner to migrate on-premises applications to a cloud infrastructure compatible with AWS, Azure and Google Cloud.', url: 'https://www.prutech.com/us/case-studies/cloud-migration/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/08/case-cloud-migration.png' },
    { level: 'Local', cat: 'Salesforce Solution', title: 'Legal Defense Trust Portal', desc: 'An independent agency of a major city needed a secure, mobile-friendly, Salesforce-powered portal to uphold ethical standards and ensure public integrity.', url: 'https://www.prutech.com/us/case-studies/salesforce-solution/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/09/Salesforce-Solution-update.png' },
    { level: 'Local', cat: 'Public Engagement', title: 'Salesforce Mobile Applications', desc: 'A city-level public engagement unit needed custom, Salesforce-powered iOS mobile apps to improve services for both citizens and staff.', url: 'https://www.prutech.com/us/case-studies/public-engagement/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/08/case-publicengagement.png' },
    { level: 'Local', cat: 'Compliance Management', title: 'Mobile Inspection Application', desc: 'A city government agency partnered with PruTech on a Microsoft Dynamics-powered, fully mobile inspection management solution that protects consumers.', url: 'https://www.prutech.com/us/case-studies/compliance-management/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/05/img-comp.png' },
    { level: 'Local', cat: 'Data Analysis', title: 'AWS Data Lake', desc: 'A division of a mayoral office built an integrated data platform to analyze the impacts of COVID-19, reduce inequality and promote economic opportunity.', url: 'https://www.prutech.com/us/case-studies/data-analysis/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/06/data-ana-update-img.png' },
    { level: 'Local', cat: 'Pandemic Response', title: 'Rapid Response Data Catalog', desc: 'A mayoral office partnered with PruTech to build a standalone data catalog supporting community-focused COVID-19 recovery efforts.', url: 'https://www.prutech.com/us/case-studies/pandemic-response/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/05/CASE-STUDIES_individual_flattened_19.png' },
    { level: 'Local', cat: 'Financial Management', title: 'Dynamic Public Portal', desc: 'A city agency partnered with PruTech on an MS Dynamics solution that protects urban communities through effective financial counseling.', url: 'https://www.prutech.com/us/case-studies/financial-management/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/05/img-financial.png' },
    { level: 'Local', cat: 'License Registration', title: 'Business Community Portal', desc: 'PruTech built a Salesforce solution that encourages online license registration and provides a communication channel for businesses.', url: 'https://www.prutech.com/us/case-studies/license-registration/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/05/License-Registration-Image.png' },
    { level: 'Local', cat: 'Urban Planning', title: 'Public Search Portal', desc: 'A department of urban planning built a Microsoft Dynamics 365 platform from the ground up with an intuitive public search portal.', url: 'https://www.prutech.com/us/case-studies/urban-planning/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/09/Urban-Plannin-update.png' },
    { level: 'Local', cat: 'Community Development', title: 'Participant Tracking System', desc: 'A city department of community development built a case tracking system making it easier for contractors to serve participants of activities.', url: 'https://www.prutech.com/us/case-studies/community-development/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/06/community-update-img-1.png' },
    { level: 'State', cat: 'Remote Learning', title: 'Parent-Friendly Application', desc: 'A government education department created a user-friendly app letting parents communicate with schools and track devices for remote learning.', url: 'https://www.prutech.com/us/case-studies/remote-learning/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/06/remote-update-img.png' },
    { level: 'Commercial', cat: 'Cloud Security', title: 'Modernized AWS Environment', desc: 'A boutique travel agency modernized its cloud infrastructure with PruTech, achieving consistent uptime and a stronger security posture.', url: 'https://www.prutech.com/us/case-studies/cloud-security/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/06/cloud-updated-img.png' },
    { level: 'Local', cat: 'Economic Equality', title: 'Master Data Management Upgrade', desc: 'A mayoral office upgraded its IBM Master Data Management system to create better master data records and promote wider economic opportunity.', url: 'https://www.prutech.com/us/case-studies/economic-equality/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/08/case-economic-equality.png' },
    { level: 'Commercial', cat: 'Data Security', title: 'Real-Time PII Protection', desc: 'A leading builder of marketing platforms installed a Privacera solution that automatically recognizes and protects personally identifiable information.', url: 'https://www.prutech.com/us/case-studies/data-security/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/09/case-Data-Security.png' },
    { level: 'Commercial', cat: 'Marketing Communications', title: 'AWS Pinpoint Service', desc: 'A publisher of peer-reviewed science journals implemented an AWS solution to improve email campaigns targeting their global network.', url: 'https://www.prutech.com/us/case-studies/marketing-communications/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/06/marketing-updated-img.png' },
    { level: 'Local', cat: 'Transforming Operations', title: 'Citizen Self-Service Tool', desc: "A major city's department of consumer and worker protection created a more efficient way to interact with consumers and the businesses they serve.", url: 'https://www.prutech.com/us/case-studies/transforming-operations/', img: 'https://www.prutech.com/us/wp-content/uploads/2023/08/case-transforming-operations.png' }
];
