/* ============================================================
   PruTech — world land mask
   A 2-degree equirectangular land/ocean grid derived from real
   coastline data, packed one bit per cell, MSB first, base64.
   Rows run north -> south from +82 to -60 latitude.
   Whole planet: ~1.3 KB.
   ============================================================ */
window.PT_WORLD = {
  latTop: 82,      // first row's latitude
  step:   2.0,     // degrees per cell
  rows:   72,
  cols:   180,     // -180 .. +177.5
  bits:   'AAAAAAAD/+ev7UAAAAAAAAAAAAAAAAAAAAAAC//h///0AALwAAAADgAAAAAAAAAAADCg+////wAAdAAAAAAIAAAAAAAAAAA+xMAA///wAAAAAAcAB/4ABAAAAAAADwBUAAP//gAAAAADAAv/gAIAAAAAAADfTC+AH/9gAAAAAMBi///+D4AAAH/gYP8434F//gAAA4AAj///////wAwP///4Zcj8D/wAAAP/xb/v////////+f/////+h7B+geAAf/H///////////AD/////908B8AcAA+/v///////////AP/////wPAA4AAAH5///////////98Af0P///gDgAAAAAH8D//////////EAAAgC///wD+AAAACA4f////////+AMAACAA///+D/AAAACBx/////////4A8AAAAA////n/wAAAZBv/////////6AwAAAAAP///3/4AAAbn///////////AQAAAAAH////4AAAAAf//////////+AAAAAAAD////4cAAAD///////////8AAAAAAAB////8gAAAA//9f///////5EAAAAAAD////0AAAAA+v4P///////xgAAAAAAD////gAAAAPwz4H//////+AAAAAAAAD///+AAAAAPoLv///////eCAAAAAAAB///+AAAAAPAZv///////GCAAAAAAAA///8AAAAAAfAA///////iOAAAAAAAAf//8AAAAAH/AA///////g4AAAAAAAAP//wAAAAAP/zg///////gAAAAAAAAAD/8QAAAAAP////v/////gAAAAAAAAAF/AQAAAAA/////v/////gAAAAAAAAAC/AAAAAAB////fx/////AAAAAAAAAABfAAAAAAB////P2D///+AAAAAAAAAAAPAoAAAAD////v/B///4AAAAAAAAAAAPGCAAAAD////n+Afx/AAAAAAAAAAAAH8AEAAAD////3+AfA/AQAAAAAAAAAAA8AAAAAD////74AeAfggAAAAAAAAAAAHgAAAAD////7AAOAPgAAAAAAAAAAAABgwAAAD////8AAMADgoAAAAAAAAAAAAheAAAB/////wAEABAAAAAAAAAAAAAAH/gAAA/////gACAIAMAAAAAAAAAAAAD/wAAAfn///gAAAEBAAAAAAAAAAAAAD/+AAAAB///AAAAUmAAAAAAAAAAAAAH/+AAAAB//+AAAAKOAAAAAAAAAAAAAP//AAAAB//8AAAAMegAAAAAAAAAAAAP//wAAAB//4AAAAHOh0AAAAAAAAAAAP//+AAAA//wAAAACAwPgAAAAAAAAAAP///gAAAf/wAAAABAAD0AAAAAAAAAAH///gAAAf/wAAAAAMAHQAAAAAAAAAAH///AAAAf/wAAAAAAoAIAAAAAAAAAAD///AAAAf/4AAAAAAARAAAAAAAAAAAD//+AAAAf/4wAAAAABxAAAAAAAAAAAB//+AAAA//5gAAAAAH5gAAAAAAAAAAAf/+AAAA//hgAAAAAP/wABAAAAAAAAAf/8AAAAf/BgAAAAA//4AAAAAAAAAAAf/8AAAAP/DgAAAAH//4AAAAAAAAAAAf/gAAAAP/DAAAAAH//8AAAAAAAAAAAf/AAAAAP+AAAAAAD//+AAAAAAAAAAAf/AAAAAP+AAAAAAD//+AAAAAAAAAAAf+AAAAAH8AAAAAAD//+AAAAAAAAAAAf+AAAAAD4AAAAAAD+f+AAAAAAAAAAAf8AAAAADgAAAAAADAP8AAAAAAAAAAA/wAAAAAAAAAAAAAAAD8AEAAAAAAAAA/wAAAAAAAAAAAAAAABwADAAAAAAAAA+AAAAAAAAAAAAAAAAAoACAAAAAAAAB8AAAAAAAAAAAAAAAAAYAMAAAAAAAAA8AAAAAAAAAAAAAAAAAAAQAAAAAAAAB4AAAAAAAAAAAAAAAAAAAwAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAABwgAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
};
